Add apix test capability to CI
In order to run hourly/gating tests for DIM/APIX this capability need to exist in CI.
This commit adds:
-APIX capability to CI (physical Bosch 12" 2015).

Change-Id: I96992c1e33f3de2082ec17109efd0b2b1dce51f1

diff --git a/tools/ci/jenkins/jenkins_job_builder/jobs/daily_job.yml b/tools/ci/jenkins/jenkins_job_builder/jobs/daily_job.yml
--- a/tools/ci/jenkins/jenkins_job_builder/jobs/daily_job.yml
+++ b/tools/ci/jenkins/jenkins_job_builder/jobs/daily_job.yml
@@ -219,3 +219,25 @@
                 - bootstrap_ihu_daily_common.sh
                 - bootstrap_common_time_triggered.sh
                 - bootstrap_ihu_daily_test_common.sh
+
+- job:
+    name: ihu_daily_test-apix
+    defaults: daily_job_defaults
+    node: daily_test-apix
+    parameters:
+        - run:
+            name: UPSTREAM_JOB
+            project-name: ihu_daily_build_vcc_eng
+            description: parameter 'UPSTREAM_JOB_RESULT' will be used to validate if the daily build has passed.
+    builders:
+        - shell: |
+            if [ "$UPSTREAM_JOB_RESULT" != "SUCCESS" ]
+            then
+                echo "Daily build ihu_vcc-eng failed!!!"
+                exit 1
+            fi
+        - shell:
+            !include-raw:
+                - bootstrap_ihu_daily_common.sh
+                - bootstrap_common_time_triggered.sh
+                - bootstrap_ihu_daily_test_common.sh
diff --git a/tools/ci/jenkins/jenkins_job_builder/jobs/hourly_job.yml b/tools/ci/jenkins/jenkins_job_builder/jobs/hourly_job.yml
--- a/tools/ci/jenkins/jenkins_job_builder/jobs/hourly_job.yml
+++ b/tools/ci/jenkins/jenkins_job_builder/jobs/hourly_job.yml
@@ -167,3 +167,24 @@
             !include-raw:
                 - bootstrap_common_time_triggered.sh
                 - bootstrap_ihu_hourly_test_common.sh
+
+- job:
+    name: ihu_hourly_test-apix
+    defaults: hourly_job_defaults
+    node: hourly_test-apix
+    parameters:
+        - run:
+            name: UPSTREAM_JOB
+            project-name: ihu_hourly_build-eng
+            description: parameter 'UPSTREAM_JOB_RESULT' will be used to validate if the hourly build has passed.
+    builders:
+        - shell: |
+            if [ "$UPSTREAM_JOB_RESULT" != "SUCCESS" ]
+            then
+                echo "Hourly test apix failed!!!"
+                exit 1
+            fi
+        - shell:
+            !include-raw:
+                - bootstrap_common_time_triggered.sh
+                - bootstrap_ihu_hourly_test_common.sh
